SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	flagadmin		BOOLEAN			NOT NULL	DEFAULT false,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);


CREATE TABLE parent (
    IdParent        INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IdCompte        INT             NOT NULL,  
    Nom             VARCHAR(50)     NOT NULL,
    Prenom          VARCHAR(50)     NOT NULL,
    AdressePostale  VARCHAR(255)    NOT NULL,
    AdresseEmail    VARCHAR(255)    NOT NULL,
    Telephone       VARCHAR(15)     NOT NULL,
    FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
    PRIMARY KEY (IdParent)
);


CREATE TABLE contrat (
    IdContrat       INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IdParent        INT             NOT NULL REFERENCES parent (IdParent) ON DELETE CASCADE,  
    NomEnfant       VARCHAR(50)     NOT NULL, 
    PrenomEnfant    VARCHAR(50)     NOT NULL,  
    DateNaissanceEnfant DATE        NOT NULL,  
    DateDebut       DATE            NOT NULL,  
    DateFin         DATE            NOT NULL,  
    TarifHoraire    DECIMAL(5, 2)   NOT NULL,  
    IndemniteEntretienTauxHoraire DECIMAL(5, 3) NOT NULL,  
    IndemniteEntretienMinimum      DECIMAL(5, 2) NOT NULL,  
    IndemniteRepas  DECIMAL(5, 2), 
    PRIMARY KEY (IdContrat)
);

CREATE TABLE garde (
    IdGarde         INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IdContrat       INT             NOT NULL REFERENCES contrat (IdContrat) ON DELETE CASCADE,  
    DateJour        DATE            NOT NULL,  
    HeureArrivee    TIME            NOT NULL,  
    HeureDepart     TIME            NOT NULL, 
    APrisRepas      BOOLEAN         NOT NULL DEFAULT false,  
    PRIMARY KEY (IdGarde)
);

CREATE TABLE tarif (
    IdTarif         INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    TypeTarif       VARCHAR(50)     NOT NULL,
    Montant         DECIMAL(5, 2)   NOT NULL,  
    PRIMARY KEY (IdTarif)
);